name: CI

on: 
  push:
    branches: develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: mvn clean compile -B
    - name: Unit tests
      run: mvn test -B
    - name: Start InfluxDB
      run: docker run -p 8086:8086 influxdb:1.7.7
    - name: Integration tests
      run: mvn verify -DskipUTs -B
